import { Router } from 'express'; import { pool } from '../db.js'; import { auth } from '../middleware/auth.js'; const router=Router();
router.get('/', auth(), async (req,res)=>{ const isOp=req.user.role==='OPERATOR'; let sql='SELECT id, client_id, store_id, gift_name, created_at FROM redemptions'; const params=[]; if(isOp){ sql+=' WHERE store_id=$1'; params.push(req.user.store_id) } sql+=' ORDER BY id DESC LIMIT 500'; const { rows } = await pool.query(sql, params); res.json(rows) });
router.post('/redeem', auth(), async (req,res)=>{ const { client_id, store_id:storeIdBody, gift_name='Brinde' } = req.body; if(!client_id) return res.status(400).json({ error:'client_id é obrigatório' }); const storeId=req.user.role==='OPERATOR'?req.user.store_id:(storeIdBody??null);
  let visits_goal=5; if(storeId){ const g=await pool.query('SELECT COALESCE(meta_visitas,5) AS goal FROM stores WHERE id=$1', [storeId]); visits_goal=g.rows[0]?.goal ?? 5 }
  const lastRed=await pool.query(`SELECT created_at FROM redemptions WHERE client_id=$1 ${storeId?'AND store_id=$2':''} ORDER BY created_at DESC LIMIT 1`, storeId?[client_id, storeId]:[client_id]); const since=lastRed.rows[0]?.created_at || '1970-01-01';
  const count=await pool.query(`SELECT COUNT(*)::int AS c FROM visits WHERE client_id=$1 ${storeId?'AND store_id=$2':''} AND created_at > $${storeId?3:2}`, storeId?[client_id, storeId, since]:[client_id, since]); if(count.rows[0].c < Number(visits_goal)) return res.status(400).json({ error:'Meta não atingida' });
  const { rows } = await pool.query('INSERT INTO redemptions (client_id, store_id, gift_name) VALUES ($1,$2,$3) RETURNING *', [client_id, storeId, gift_name]); res.status(201).json(rows[0]);
});
router.get('/export', auth(), async (req,res)=>{ const isOp=req.user.role==='OPERATOR'; const params=[]; let sql=`SELECT r.id, r.client_id, c.name as client_name, r.gift_name, r.store_id, to_char(r.created_at,'YYYY-MM-DD HH24:MI:SS') as created_at FROM redemptions r JOIN clients c ON c.id=r.client_id`; if(isOp){ sql+=' WHERE r.store_id=$1'; params.push(req.user.store_id) } sql+=' ORDER BY r.id DESC'; const { rows } = await pool.query(sql, params); const header='id;client_id;client_name;gift_name;store_id;created_at\n'; const body=rows.map(r=>[r.id,r.client_id,r.client_name,r.gift_name,r.store_id || '',r.created_at || ''].join(';')).join('\n'); res.setHeader('Content-Type','text/csv; charset=utf-8'); res.setHeader('Content-Disposition','attachment; filename="redemptions.csv"'); res.send('\ufeff'+header+body) });
export default router;
